# Generated by Django 3.2.8 on 2021-11-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20211103_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='favourite',
        ),
    ]
