# Generated by Django 3.2.8 on 2021-10-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='symbol',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
